name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # Matou App Version
      - name: Get app version
        id: version
        run: |
          echo "VERSION=$(node -p "require('./frontend/package.json').version")" >> $GITHUB_ENV

      # Platform name
      - name: Set platform name
        id: platform
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            echo "PLATFORM=linux" >> $GITHUB_ENV
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            echo "PLATFORM=mac" >> $GITHUB_ENV
          elif [[ "${RUNNER_OS}" == "Windows" ]]; then
            echo "PLATFORM=windows" >> $GITHUB_ENV
          fi


      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      # Install Quasar CLI
      - name: Install Quasar CLI
        run: npm install -g @quasar/cli

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: false

      # Backend set up
      - name: Prepare backend modules
        run: |
          cd backend
          go mod tidy

      # Build backend
      - name: Build backend
        shell: bash {0}
        run: |
          cd backend
          if [ "$RUNNER_OS" == "Linux" ]; then
            make build-linux-amd64
          elif [ "$RUNNER_OS" == "macOS" ]; then
            make build-darwin-amd64 # MacOS Intel
            make build-darwin-arm64 # MacOS Apple Silicone
          elif [ "$RUNNER_OS" == "Windows" ]; then
            make build-windows-amd64
          fi


      # Build Electron app
      - name: Build Electron App
        shell: bash {0}
        run: |
          cd frontend
          # Linux
          if [ "$RUNNER_OS" == "Linux" ]; then
            npx quasar build -m electron
          # macOS
          elif [ "$RUNNER_OS" == "macOS" ]; then
            npx quasar build -m electron --mac --x64 # MacOS Intel
            npx quasar build -m electron --mac --arm64 # MacOS Apple Silicone
          # Windows
          elif [ "$RUNNER_OS" == "Windows" ]; then
            npx quasar build -m electron --win
          fi

      # Upload artifacts
      - name: Upload packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: matou-${{ env.VERSION }}-${{ env.PLATFORM }}
          path: |
            frontend/dist/electron/Packaged/matou-*.AppImage
            frontend/dist/electron/Packaged/matou-*.exe
            frontend/dist/electron/Packaged/matou-*-mac-*.dmg
            # todo add other files needed

