name: Matou App Build

# when a new tag is pushed, it will run this workflow
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    strategy:
      matrix:
        include:
        - os: macos-15-intel
          platform: mac
          arch: x64
          make_target: build-darwin-amd64

        - os: macos-latest
          platform: mac
          arch: arm64
          make_target: build-darwin-arm64

        - os: ubuntu-latest
          platform: linux
          arch: amd64
          make_target: build-linux-amd64

        - os: windows-latest
          platform: windows
          arch: amd64
          make_target: build-windows-amd64

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # Matou App Version
      - name: Get app version
        id: version
        shell: bash
        run: |
          echo "VERSION=$(node -p "require('./frontend/package.json').version")" >> $GITHUB_ENV

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      # Install Quasar CLI
      - name: Install Quasar CLI
        run: npm install -g @quasar/cli

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: false

      # Backend set up
      - name: Prepare backend modules
        run: |
          cd backend
          go mod tidy

      # Build backend
      - name: Build backend
        shell: bash {0}
        run: |
          cd backend
          make ${{ matrix.make_target }}

      # Setup macOS Signing
      - name: Setup macOS Signing (if mac)
        if: matrix.platform == 'mac'
        shell: bash
        run: |
          cd frontend
          # write Apple API key from secret
          echo "${{ secrets.APPLE_API_KEY_CONTENT }}" > AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8

      # Build Electron app
      - name: Build Electron App
        shell: bash {0}
        run: |
          cd frontend
          
          if [[ "${{ matrix.platform }}" == "mac" ]]; then
            npx quasar build -m electron --mac --${{ matrix.arch }}
          else
            npx quasar build -m electron
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_API_KEY: AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      # Upload artifacts
      # - name: Upload ${{ matrix.platform }} artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
          
      #     name: matou-${{ env.VERSION }}-${{ matrix.platform }}-${{ matrix.arch }}
      #     path: |
      #       frontend/dist/electron/Packaged/**
      #       # frontend/dist/electron/Packaged/**/*.dmg
      #       # frontend/dist/electron/Packaged/**/*.exe
      #       # frontend/dist/electron/Packaged/**/*.AppImage
      #     if-no-files-found: ignore
